### ISSUE TITLE
Download update from custom url

### ISSUE THREAD

**Issue by Kirkan** [btkelly/gandalf#57]
Hi!
How can I upload my update not through Google Play service?
Thank you!

**Comment by stkent** [comment]
Not possible currently, though it wouldn't be too hard to support. Will see what @btkelly thinks of this as a feature request.

**Comment by Kirkan** [comment]
For me it will be enough:
`private static Uri getGooglePlayStoreUriForPackageName(@NonNull final String packageName) {
        if(packageName.contains(".apk"))
            return Uri.parse(packageName);
        else
            return Uri.parse(GOOGLE_PLAY_STORE_URI_PREFIX + packageName);
    }`

**Comment by btkelly** [comment]
I do like the option to handle different actions based on user selection but I'm not sure just adding one other way to do this is best. Mainly because I cannot predict all the possible requirements a user may have.

I'm thinking we should add an interface for answering a question and provide default implementations of these interfaces that perform the current actions. This would allow a consumer to add any behavior they desire or just use the current behavior.
