### ISSUE TITLE
Asyncronous update checking

### ISSUE THREAD

**Issue by jeffbordon** [btkelly/gandalf#76]
The GandalfActivity approach blocks the UI leading to a unwanted delay on startup.

Is there any example of how to use Gandalf e.g. with a background Service/IntentService?

**Comment by btkelly** [comment]
First I just want to point out that it is intentional that `GandalfActivity` blocks the UI. This is because when issuing a force update it is usually related to some unforeseen event or bug found in the future. Without knowing which section of the app the update is for you risk executing code that should not be executing before the Gandalf check can complete.

But Gandalf is built in such a way that you can use it however you would like to get the same update functionality. The `README` has a quick explanation about using Gandalf without the `Activity` approach:

> If extending GandalfActivity doesn't work for you the Gandalf class can be used directly by calling shallIPass(GandalfCallback callback). In this case make sure you respond to the callback methods and make a call to gandalf.save(Alert alert) and gandalf.save(OptionalUpdate optionalUpdate) if not using the BootstrapDialogUtil for your UI.

Let me know if that isn't clear enough or you need a little more direction.

**Comment by jeffbordon** [comment]
OK, thanks. I got your point why using a splash activity makes sense.

Another idea to minimize the unwanted delay could be adjusting the http request timeout as this especially happens with bad internet connection. However, this would increase the risk of passing the check simply due to a timeout.

**Comment by btkelly** [comment]
That is a possible solution to avoid long delays during the Gandalf check. You can accomplish this by passing a custom `OkHttpClient` to the `Installer` and setting your own timeout length. The current [default](https://github.com/btkelly/gandalf/blob/master/gandalf/src/main/java/io/github/btkelly/gandalf/network/BootstrapApi.java#L73) for Gandalf is set to 30 seconds.
